services:
  postgres:
    image: bitnami/postgresql:15.8.0
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_PASSWORD=postgres
  kafka:
    image: bitnami/kafka:3.8
    ports:
      - 9092:9092
    volumes:
      - kafka_data:/bitnami
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://172.17.0.1:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - 9091:8080
    depends_on:
      - kafka
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=172.17.0.1:9092
      - DYNAMIC_CONFIG_ENABLED='true'
  apprise:
    image: caronc/apprise:1.1
    ports:
      - 8000:8000
    volumes:
      - apprise:/config
  minio:
    image: bitnami/minio:2024.8.17
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    volumes:
      - minio_data:/bitnami/minio/data
  elasticsearch:
    image: bitnami/elasticsearch:8.15.0
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch_data:/bitnami/elasticsearch/data
  kibana:
    image: bitnami/kibana:8.15.0
    ports:
      - 5601:5601
    environment:
      - KIBANA_ELASTICSEARCH_URL=172.17.0.1
  keycloak-postgres:
    image: bitnami/postgresql:15.8.0
    volumes:
      - keycloak_postgres_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_PASSWORD=postgres
  keycloak:
    image: bitnami/keycloak:25.0.5
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_DATABASE_HOST=keycloak-postgres
      - KEYCLOAK_DATABASE_USER=postgres
      - KEYCLOAK_DATABASE_NAME=postgres
      - KEYCLOAK_DATABASE_PASSWORD=postgres
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    depends_on:
      - keycloak-postgres
  hasura-postgres:
    image: bitnami/postgresql:15.8.0
    volumes:
      - hasura_postgres_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_PASSWORD=postgres
  hasura:
    image: hasura/graphql-engine:v2.43.0
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgres@hasura-postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: "startup, http-log, webhook-log, websocket-log, query-log"
      HASURA_GRAPHQL_ADMIN_SECRET: "admin"
      HASURA_GRAPHQL_JWT_SECRET: "{\"jwk_url\": \"http://172.17.0.1:8080/realms/dev/protocol/openid-connect/certs\"}"
    ports:
      - 8081:8080
    depends_on:
      - hasura-postgres

volumes:
  postgres_data:
    driver: local
  kafka_data:
    driver: local
  apprise:
    driver: local
  minio_data:
    driver: local
  elasticsearch_data:
    driver: local
  hasura_postgres_data:
    driver: local
  keycloak_postgres_data:
    driver: local
